#!/usr/bin/python

# Strings in Python

str = 'Hello World!'

# If you see a output message complete string
print(str)

# You will get the first character of the string
print("first character of the string: ", str[0])

# When required the string starting from 3rd to 5th
print("the string starting from 3rd to 5th: ",str[2:5])

# When required the string starting from 3rd character
print("the string starting from 3rd to 5th: ",str[2:])

# to print string two times
print("the string two times: ",str * 2)

# to print concatenated string with "TEST"
print("concatenated string : ", str + "TEST")